"""initial schema

Revision ID: f673c8b4ba27
Revises: 
Create Date: 2026-03-29 07:35:56.686342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'f673c8b4ba27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_packages'))
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('tiku_cache_entries',
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiku_cache_entries'))
    )
    op.create_index(op.f('ix_tiku_cache_entries_question_hash'), 'tiku_cache_entries', ['question_hash'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('invite_code_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_users_invited_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('invites',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('bonus_credits', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_invites_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites'))
    )
    op.create_index(op.f('ix_invites_code'), 'invites', ['code'], unique=True)
    op.create_foreign_key(
        op.f('fk_users_invite_code_id_invites'),
        'users',
        'invites',
        ['invite_code_id'],
        ['id'],
    )
    op.create_table('chaoxing_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('auth_type', sa.Enum('PASSWORD', 'COOKIES', name='chaoxingauthtype'), nullable=False),
    sa.Column('username_encrypted', sa.Text(), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('cookies_encrypted', sa.Text(), nullable=True),
    sa.Column('is_login_valid', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chaoxing_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chaoxing_accounts'))
    )
    op.create_index(op.f('ix_chaoxing_accounts_user_id'), 'chaoxing_accounts', ['user_id'], unique=False)
    op.create_table('recharge_orders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('requested_credits', sa.Integer(), nullable=False),
    sa.Column('payment_channel', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('proof_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='rechargeorderstatus'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['credit_packages.id'], name=op.f('fk_recharge_orders_package_id_credit_packages')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_recharge_orders_reviewed_by_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recharge_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recharge_orders'))
    )
    op.create_index(op.f('ix_recharge_orders_package_id'), 'recharge_orders', ['package_id'], unique=False)
    op.create_index(op.f('ix_recharge_orders_status'), 'recharge_orders', ['status'], unique=False)
    op.create_index(op.f('ix_recharge_orders_user_id'), 'recharge_orders', ['user_id'], unique=False)
    op.create_table('study_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('speed', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('notopen_action', sa.Enum('RETRY', 'CONTINUE', name='notopenaction'), nullable=False),
    sa.Column('tiku_config', sa.JSON(), nullable=False),
    sa.Column('submit_config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_profiles'))
    )
    op.create_index(op.f('ix_study_profiles_user_id'), 'study_profiles', ['user_id'], unique=False)
    op.create_table('tiku_providers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.Enum('YANXI', 'LIKE', 'ADAPTER', 'OPENAI_COMPAT', 'SILICONFLOW', name='tikuprovidertype'), nullable=False),
    sa.Column('config_encrypted', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tiku_providers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiku_providers'))
    )
    op.create_index(op.f('ix_tiku_providers_user_id'), 'tiku_providers', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('user_id', name=op.f('uq_wallets_user_id'))
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('study_runs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('course_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'STOPPING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='studyrunstatus'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('progress_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['chaoxing_accounts.id'], name=op.f('fk_study_runs_account_id_chaoxing_accounts')),
    sa.ForeignKeyConstraint(['profile_id'], ['study_profiles.id'], name=op.f('fk_study_runs_profile_id_study_profiles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_runs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_runs'))
    )
    op.create_index(op.f('ix_study_runs_account_id'), 'study_runs', ['account_id'], unique=False)
    op.create_index(op.f('ix_study_runs_celery_task_id'), 'study_runs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_study_runs_profile_id'), 'study_runs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_study_runs_status'), 'study_runs', ['status'], unique=False)
    op.create_index(op.f('ix_study_runs_user_id'), 'study_runs', ['user_id'], unique=False)
    op.create_table('study_run_events',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', name='studyruneventlevel'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['study_runs.id'], name=op.f('fk_study_run_events_run_id_study_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_run_events'))
    )
    op.create_index(op.f('ix_study_run_events_run_id'), 'study_run_events', ['run_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('related_run_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['related_run_id'], ['study_runs.id'], name=op.f('fk_wallet_transactions_related_run_id_study_runs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallet_transactions_user_id_users')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('fk_wallet_transactions_wallet_id_wallets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_transactions'))
    )
    op.create_index(op.f('ix_wallet_transactions_related_run_id'), 'wallet_transactions', ['related_run_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_related_run_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_study_run_events_run_id'), table_name='study_run_events')
    op.drop_table('study_run_events')
    op.drop_index(op.f('ix_study_runs_user_id'), table_name='study_runs')
    op.drop_index(op.f('ix_study_runs_status'), table_name='study_runs')
    op.drop_index(op.f('ix_study_runs_profile_id'), table_name='study_runs')
    op.drop_index(op.f('ix_study_runs_celery_task_id'), table_name='study_runs')
    op.drop_index(op.f('ix_study_runs_account_id'), table_name='study_runs')
    op.drop_table('study_runs')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_tiku_providers_user_id'), table_name='tiku_providers')
    op.drop_table('tiku_providers')
    op.drop_index(op.f('ix_study_profiles_user_id'), table_name='study_profiles')
    op.drop_table('study_profiles')
    op.drop_index(op.f('ix_recharge_orders_user_id'), table_name='recharge_orders')
    op.drop_index(op.f('ix_recharge_orders_status'), table_name='recharge_orders')
    op.drop_index(op.f('ix_recharge_orders_package_id'), table_name='recharge_orders')
    op.drop_table('recharge_orders')
    op.drop_index(op.f('ix_chaoxing_accounts_user_id'), table_name='chaoxing_accounts')
    op.drop_table('chaoxing_accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(op.f('fk_users_invite_code_id_invites'), 'users', type_='foreignkey')
    op.drop_table('users')
    op.drop_index(op.f('ix_tiku_cache_entries_question_hash'), table_name='tiku_cache_entries')
    op.drop_table('tiku_cache_entries')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_invites_code'), table_name='invites')
    op.drop_table('invites')
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
